enum Theme {
  BLACK = 'black',
  WHITE = 'white',
  LEAGUE = 'league',
  BEIGE = 'beige',
  SKY = 'sky',
  NIGHT = 'night',
  SERIF = 'serif',
  SIMPLE = 'simple',
  SOLARIZED = 'solarized',
  BLOOD = 'blood',
  MOON = 'moon',
}

const Themes = [
  Theme.BLACK,
  Theme.WHITE,
  Theme.LEAGUE,
  Theme.BEIGE,
  Theme.SKY,
  Theme.NIGHT,
  Theme.SERIF,
  Theme.SIMPLE,
  Theme.SOLARIZED,
  Theme.BLOOD,
  Theme.MOON,
];

enum ThemeVariable {
  BACKGROUND_COLOR = 'backgroundColor',
  MAIN_FONT = 'mainFont',
  MAIN_FONT_SIZE = 'mainFontSize',
  MAIN_COLOR = 'mainColor',
  BLOCK_MARGIN = 'blockMargin',
  HEADING_MARGIN = 'headingMargin',
  HEADING_FONT = 'headingFont',
  HEADING_COLOR = 'headingColor',
  HEADING_LINE_HEIGHT = 'headingLineHeight',
  HEADING_LETTER_SPACING = 'headingLetterSpacing',
  HEADING_TEXT_TRANSFORM = 'headingTextTransform',
  HEADING_TEXT_SHADOW = 'headingTextShadow',
  HEADING_FONT_WEIGHT = 'headingFontWeight',
  HEADING1_TEXT_SHADOW = 'heading1TextShadow',
  HEADING1_SIZE = 'heading1Size',
  HEADING2_SIZE = 'heading2Size',
  HEADING3_SIZE = 'heading3Size',
  HEADING4_SIZE = 'heading4Size',
  CODE_FONT = 'codeFont',
  LINK_COLOR = 'linkColor',
  LINK_COLOR_HOVER = 'linkColorHover',
  SELECTION_BACKGROUND_COLOR = 'selectionBackgroundColor',
  SELECTION_COLOR = 'selectionColor',
}

const ThemeOptions = [
  'name',
  ThemeVariable.BACKGROUND_COLOR,
  ThemeVariable.MAIN_FONT,
  ThemeVariable.MAIN_FONT_SIZE,
  ThemeVariable.MAIN_COLOR,
  ThemeVariable.BLOCK_MARGIN,
  ThemeVariable.HEADING_MARGIN,
  ThemeVariable.HEADING_FONT,
  ThemeVariable.HEADING_COLOR,
  ThemeVariable.HEADING_LINE_HEIGHT,
  ThemeVariable.HEADING_LETTER_SPACING,
  ThemeVariable.HEADING_TEXT_TRANSFORM,
  ThemeVariable.HEADING_TEXT_SHADOW,
  ThemeVariable.HEADING_FONT_WEIGHT,
  ThemeVariable.HEADING1_TEXT_SHADOW,
  ThemeVariable.HEADING1_SIZE,
  ThemeVariable.HEADING2_SIZE,
  ThemeVariable.HEADING3_SIZE,
  ThemeVariable.HEADING4_SIZE,
  ThemeVariable.CODE_FONT,
  ThemeVariable.LINK_COLOR,
  ThemeVariable.LINK_COLOR_HOVER,
  ThemeVariable.SELECTION_BACKGROUND_COLOR,
  ThemeVariable.SELECTION_COLOR,
];

export { Themes, ThemeOptions };
